cargo-features = ["edition2021"]

[package]
name = "fend"
# Don't bump version numbers manually, use deploy.sh instead
version = "1.0.1"
authors = ["printfn <printfn@users.noreply.github.com>"]
description = "Arbitrary-precision unit-aware calculator"
homepage = "https://github.com/printfn/fend"
repository = "https://github.com/printfn/fend"
readme = "README.md"
license = "MIT"
keywords = ["calculator", "cli", "conversion", "math", "tool"]
edition = "2021"
categories = ["command-line-utilities", "mathematics", "science"]

[package.metadata.nix]
build = true
toolchain = "nightly"

[dependencies]
rustyline = { version =  "9.1.4", default-features = false, package = "rustyline-with-hint-fix" }
home = "0.5.3"
ctrlc = "3.2.1"
ansi_term = "0.12.1"
toml = "0.5.8"
serde = { version = "1.0.136", default-features = false }
nanorand = { version = "0.6.1", default-features = false, features = ["std", "wyrand"] }
#console = { version = "0.15.0", default-features = false }
atty = "0.2.14"

[dependencies.fend-core]
version = "1.0.1"
path = "../core"
